### ISSUE TITLE
ModuleNotFoundError: No module named 'neuralintents'

### ISSUE THREAD

**Issue by sanikava** [just-innovative-bro/F.R.I.D.A.Y#51]
from neuralintents import GenericAssistant
ModuleNotFoundError: No module named 'neuralintents'

**Comment by Zameel-Byte** [comment]
Make sure that neuralintents module is installed on your PC.
If not use this command "pip install neuralintents".

**Comment by sanikava** [comment]
> Make sure that neuralintents module is installed on your PC. If not use this command "pip install neuralintents".

I did but this module not installing

**Comment by Zameel-Byte** [comment]
Can I know which workspace you are using

**Comment by sanikava** [comment]
> Can I know which workspace you are using

Im using windows 11

**Comment by Zameel-Byte** [comment]
Which version of python you are using

**Comment by sanikava** [comment]
> Which version of python you are using

Python 3.8.10

**Comment by sanikava** [comment]
I think i have to try with Python 3.9.7

**Comment by sanikava** [comment]
@Zameel-Byte 
ERROR: Could not find a version that satisfies the requirement tensorflow==2.9.1 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.9.1

after updating python to 3.9.7 i am still getting error for tensorflow

**Comment by Zameel-Byte** [comment]
For tensorflow you should enable long paths

**Comment by Zameel-Byte** [comment]
While installing python at last it show close or enable path, options

**Comment by Zameel-Byte** [comment]
I hope your issue is solved
